name: Action Test
on:
  workflow_dispatch: {}

jobs:
  reminder:
    name: test
    runs-on: ubuntu-22.04
    steps:
      - name: File Issue
        id: file-issue
        uses: paketo-buildpacks/github-config/actions/issue/file@main
        with:
          token: ${{ secrets.ARJUN024_PROJECT_TOKEN }}
          repo: ${{ github.repository }}
          issue_title: "test"
          issue_body: |
            Foo
            ```
            Bar
            ```
