name: Go version + Umask
on:
  workflow_dispatch: {}

jobs:
  reminder:
    name: test
    runs-on: ubuntu-22.04
    steps:
      - name: Print Picked Version
        run: |
          echo "go version"
          go version
      - name: Print umask
        run: |
          echo "umask"
          umask
