name: Go version + Umask + Dock daemon
on:
  workflow_dispatch: {}

jobs:
  reminder:
    name: test
    runs-on: ubuntu-22.04
    steps:
      - name: Print Picked Version
        run: |
          echo "go version"
          go version
      - name: Print umask
        run: |
          echo "umask"
          umask
      - name: Test skopeo
        run: |
          skopeo list-tags docker://cloudfoundry/cflinuxfs4 | jq -r '.Tags'
      - name: Docker daemon test
        run: |
          echo "images:"
          docker image ls
          
