name: Go version + Umask + Dock daemon
on:
  workflow_dispatch: {}

jobs:
  reminder:
    name: test
    runs-on: ubuntu-22.04
    steps:
      - name: Print Picked Version
        run: |
          echo "go version"
          go version
      - name: Print umask
        run: |
          echo "umask"
          umask
      - name: Wait for rootfs docker image
        run: |
          version="1.20.0"
          until eval "$(
            skopeo list-tags docker://cloudfoundry/cflinuxfs4 \
              | jq -r \
              --arg VERSION "${version}" \
              '.Tags| any(. == $VERSION)')" ; do
            echo "Waiting 30s for index.docker.io/cloudfoundry/cflinuxfs4:${version} to be available"
            sleep 30
          done
          echo "image index.docker.io/cloudfoundry/cflinuxfs4:${version} is available"
      - name: Docker daemon test
        run: |
          echo "images:"
          docker image ls
          
